config/routes.rb
Rails.application.routes.draw do
  get 'bloqueos/index'
  mount ActionCable.server => "/cable"
  get 'cobranzas/list'
  get 'cobranzas/new'
  resources :loans
  get 'loans/list'
  get 'loans/create'
  get 'loans/show'
  get 'reportes/ventas'
  get 'reportes/cobros'
  get 'reportes/comisiones'
  get 'reportes/estado'
  get 'reportes/general'
  get 'reportes/almacen'
  get 'reportes/reparaciones'
  get 'reportes/alertas'
  get 'reportes/logs'
  get 'notify/list'
  get 'notify/show/:id', to: "notify#show"
  get '/deudas', to: "cobranzas#deudas"
  resources :alarms
  resources :repairs
  get 'panel/init'
  get 'interative/maps'
  resources :cobros
  resources :pos
  resources :shippings do
    get :barcode, on: :member
    get :entrace, on: :member
    get :goware, on: :member
    get :modified, on: :member

  end
  resources :products
  get 'estadistics/welcome'
  resources :providers
  resources :consortia
  resources :categories
  resources :sectores
  resources :warehouses
  resources :cobradores
  resources :collectors
  resources :modelos
  resources :brands
  resources :zones
  devise_for :users
  root 'welcome#index'

  # Filtros
  get '/products_q', to: "products#search"
  get '/shippings_q', to: "shippings#search"
  get '/alerts_q', to: "alarms#alerts_q"
  get '/consortia_q', to: "consortia#consortia_q"
  get '/loan_q', to: "loans#loan_q"

  # Filtro Reporte
  get '/general_q', to: "reportes#generalQ"
  get '/reparaciones_q', to: "reportes#reparaciones_q"
  get '/logs_q', to: "reportes#logsQ"
  get '/notify_q', to: "notify#notify_q"
  get '/alertas_q', to: "reportes#alertas_q"
  get '/ventas_q', to: "reportes#ventas_q"
  get '/cobros_q', to: "reportes#cobros_q"
  get '/estado_q', to: "reportes#estado_q"
  get '/comisiones_q', to: "reportes#comisiones_q"
  # Saves
  post 'shipping/save', to: "shippings#save"


  namespace :api do

    #==============================================================>
    # Externas:
    #==============================================================>
      #Entrada de efectivo
      get 'setBillIn/:pos/:amount', to: "app#setBillIn"

      #Salida de efectivo
      get 'setBillOut/:pos/:amount', to: "app#setBillOut"

      #Apagar Maquina
      get 'shutdown/:pos', to: "app#shutdown"

      #Encender Maquina
      get 'poweron/:pos', to: "app#powerOn"

      #Buscar la localizacion de la maquina
      get 'getLocation/:pos', to: "app#getLocation"

      #Reportar aproximidad
      get 'setAproximidad/:pos', to: "app#setAproximidad"

      #Reportar Apagado
      get 'setShutDown/:pos', to: "app#setShutDown"

      #Reportar Encendido
      get 'setPowerOn/:pos', to: "app#setPoweOn"

      #Reportar conexion de wifi
      get 'setWifiOn/:pos', to: "app#setWifiOn"

      #Reportar desconexion de wifi
      get 'setWifiOff/:pos', to: "app#setWifiOff"

      #Reportar conexion a datos
      get 'setDataOn/:pos', to: "app#setDataOn"
      
      #Reportar desconexion a datos
      get 'setDataOff/:pos', to: "app#setDataOff"

      #Reporte de localizacion
      get 'setLocations/:pos/:lon/:lat', to: "app#setLocations"

      #Traer la configuracion
      get 'getConfigByNumber/:number', to: "app#getConfigByNumber"
    #==============================================================>
    # TEST
    #==============================================================>
    get 'test/poweroff', to: "app#POWEROFF_TEST"
    get 'test/poweron', to: "app#POWERON_TEST"


    #==============================================================>
    # Internal APIs
    #==============================================================>
    #Traer Prestamos pendientes
    #get 'getPrestamosPendientes/:pos', to: "app#getPrestamosPendientes"

    #Traer direcciones
    get 'getDirections/:zone/:status', to: "app#getDirections"

    # Traer controles
    get 'getControls/:pos', to: "app#getControl"

    # Buscar entrada especifica en almacen
    get 'getEntrance/:q_for/:ref', to: "app#getEntrance"

    # Actualizar Cambios a una entrada en especifico
    get 'changeEntrace/:id/:barcode/:ref', to: "app#changeEntrace"

    # Validando un dispositivo
    post 'CheckDevice/:barcode/:t', to: "app#checkDevice"

    # Metodo para traer las zonas de un cobrador
    post 'getCollectorZone/:c_id', to: "app#getCollectorZone"

    # Metodo para traer POS por zonas
    get 'getPOSZone/:z_id', to: "app#getPOSZone"

    # Metodo para traer zonas
    get 'getZones/', to: "app#getZones"

    # Metodo para traer zonas
    get 'getCasinos/', to: "app#getCasinos"

    # Metodo para traer deuda por POS
    get 'getDebt/:pos', to: "app#getDebt"
    
    #Metodo para traer las zonas de los cobraodres
    get 'getZoneByCobrador/:cobrador', to: "app#getZoneByCobrador"
    #==============================================================>
    #                      CRONS
    #==============================================================>
    get '/crons/GHWK5_Alarms/:token', to: "app#cron_alarms"
    get '/crons/GSWT5_Hours/:token', to: "app#cron_hours"
    get '/crons/GVFT5_Mora/:token', to: "app#cron_moras"

    #==============================================================>
    #                      Estadisticas
    #==============================================================>
    get '/estadisticas/ventas/diaria', to: "app#estVentasDiaria"
    
    #==============================================================>
  
  end

  namespace :internal do

    #verificando dispositvos
    get 'CheckDevice/:barcode/:t', to:"internal#checkDevice"

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cobro.rb
class Cobro < ApplicationRecord
end

app/controllers/cobros_controller.rb
class CobrosController < ApplicationController
  before_action :set_cobro, only: [:show, :edit, :update, :destroy]

  # GET /cobros
  # GET /cobros.json
  def index
    @cobros = Cobro.all
  end

  # GET /cobros/1
  # GET /cobros/1.json
  def show
  end

  # GET /cobros/new
  def new
    @cobro = Cobro.new
  end

  # GET /cobros/1/edit
  def edit
  end

  # POST /cobros
  # POST /cobros.json
  def create
    @cobro = Cobro.new(cobro_params)

    respond_to do |format|
      if @cobro.save
        format.html { redirect_to @cobro, notice: 'Cobro was successfully created.' }
        format.json { render :show, status: :created, location: @cobro }
      else
        format.html { render :new }
        format.json { render json: @cobro.errors, status: :unprocessable_entity }
      end
    end
  end

  #Administracion Role
  # PATCH/PUT /cobros/1
  # PATCH/PUT /cobros/1.json
  def update
    respond_to do |format|
      if @cobro.update(cobro_params)
        format.html { redirect_to @cobro, notice: 'Cobro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cobro }
      else
        format.html { render :edit }
        format.json { render json: @cobro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cobros/1
  # DELETE /cobros/1.json
  def destroy
    @cobro.destroy
    respond_to do |format|
      format.html { redirect_to cobros_url, notice: 'Cobro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cobro
      @cobro = Cobro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cobro_params
      params.require(:cobro).permit(:cobradore_id, :pos_id, :pago_entrega, :pago_comision, :pago_prestamo)
    end
end

app/helpers/cobros_helper.rb
module CobrosHelper
end

app/views/cobros/_form.html.erb
<style>
#shop_t i{

  font-size:28px;

}
</style>

<nav aria-label="breadcrumb ">
  <ol class="breadcrumb bg-black">
    <li class="breadcrumb-item"><a href="/cobros">Cobros</a></li>
    <li class="breadcrumb-item active" aria-current="page">Agregar / Editar</li>
  </ol>
</nav>

<%= form_with(model: cobro, local: true) do |form| %>
  <% if cobro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cobro.errors.count, "error") %> prohibited this cobro from being saved:</h2>

      <ul>
      <% cobro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row" id="shop_t">



  <div class="col-md-3 offset-md-1">
  <div class="card card-body bg-white">
<center>
  <i class="fa fa-comments-dollar" style="color:#32a852;"></i><br>
  <h6 id="entrega">$0.00</h6>

</center>


  </div>
  </div>


  <div class="col-md-3">
  <div class="card card-body bg-white">
<center>
    <i class="fa fa-hand-holding-usd" style="color:#ed8524;"></i><br>
  <h6 id="comision">$0.00</h6>
</center>




  </div>
  </div>


  <div class="col-md-3">
  <div class="card card-body bg-white">
<center>
<h5 style="color:#912810;">Total</h5>
<h6 id="complete">$0.00</h6>
</center>



  </div>

  <br><br>


  </div>



  
  </div>

<div class="card card-body bg-white col-md-12">
<h2 class="text-muted">Cobros</h2>
<hr>

<table class="table table-striped">
<thead class="text-yellow " style="background-color:#191b1c; color:yellow;">
<th>Cobrador</th><th>Punto de Venta</th><th>Entrega</th><th>Comision</th>
</thead>

<tbody>
<tr>
      <td>

             <%=
    form.collection_select(
    :cobradore_id, # field name

    Cobradore.where(user_id: current_user.id), 
    # then you should specify methods for generating options
    :id, # this is name of method that will be called for every row, result will be set as key
    :name, # this is name of method that will be called for every row, result will be set as value
    :prompt => false # then you can specify some params. You can find them in the docs.
    )
  %>

    </td>

          <td>

    <%=
    form.collection_select(
    :pos_id, # field name

    Po.where(user_id: current_user.id), 
    :id, # this is name of method that will be called for every row, result will be set as key
    :description, # this is name of method that will be called for every row, result will be set as value

    :prompt => false # then you can specify some params. You can find them in the docs.
    )
  %>

    </td>

    <td>
        <%= form.number_field :pago_entrega, class:"form-control", placeholder:"0", style:"width:150px;" %>

    </td>

    <td>
        <%= form.number_field :pago_comision, class:"form-control", placeholder:"0", style:"width:150px;" %>

    </td>
</tr>
</tbody>

</table>


</div>

<br>
<div class="row">

<div class="card card-body bg-white col-md-5 " style="margin-left:15px;">
<h2 class="text-muted">Préstamos Pendientes</h2>
<hr>

<table class="table table-striped">
<thead class="text-yellow " style="background-color:#191b1c; color:yellow;">
<th>Code</th>
<th>Concepto</th>
<th>Monto</th>
<th>Balance</th>


</thead>
<tbody>

<tr>

</tr>

</tbody>
</table>
</div>

<div class="card card-body bg-white col-md-5 offset-md-1">
<h2 class="text-muted">Nuevo Préstamo</h2>
<hr>

<table class="table table-striped">
<thead class="text-yellow " style="background-color:#191b1c; color:yellow;">
<th>Concepto</th>
<th>Monto</th>


</thead>
<tbody>

</tbody>
</table>
</div>

</div>
  <div class="actions"><br><br>
  <center>
   
   <%= form.submit "Realizar Cobro", class:"btn btn-info" %>
  
  </center>
   
  </div>
<% end %>


<script>
$("select").select2({width: 190});

</script>

app/views/cobros/edit.html.erb
<%= render 'form', cobro: @cobro %>

app/views/cobros/index.html.erb
<nav aria-label="breadcrumb ">
  <ol class="breadcrumb bg-black">
    <li class="breadcrumb-item"><a href="#">Cobranzas</a></li>
    <li class="breadcrumb-item active" aria-current="page">Cobros</li>
  </ol>
</nav>


<h1>Cobros</h1>

<table>
  <thead>
    <tr>
      <th>Cobradore</th>
      <th>Pos</th>
      <th>Pago entrega</th>
      <th>Pago comision</th>
      <th>Pago prestamo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cobros.each do |cobro| %>
      <tr>
        <td><%= cobro.cobradore_id %></td>
        <td><%= cobro.pos_id %></td>
        <td><%= cobro.pago_entrega %></td>
        <td><%= cobro.pago_comision %></td>
        <td><%= cobro.pago_prestamo %></td>
        <td><%= link_to 'Show', cobro %></td>
        <td><%= link_to 'Edit', edit_cobro_path(cobro) %></td>
        <td><%= link_to 'Destroy', cobro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cobro', new_cobro_path %>

app/views/cobros/new.html.erb
<%= render 'form', cobro: @cobro %>

app/views/cobros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cobradore:</strong>
  <%= @cobro.cobradore_id %>
</p>

<p>
  <strong>Pos:</strong>
  <%= @cobro.pos_id %>
</p>

<p>
  <strong>Pago entrega:</strong>
  <%= @cobro.pago_entrega %>
</p>

<p>
  <strong>Pago comision:</strong>
  <%= @cobro.pago_comision %>
</p>

<p>
  <strong>Pago prestamo:</strong>
  <%= @cobro.pago_prestamo %>
</p>

<%= link_to 'Edit', edit_cobro_path(@cobro) %> |
<%= link_to 'Back', cobros_path %>