config/routes.rb
Rails.application.routes.draw do
  get 'bloqueos/index'
  mount ActionCable.server => "/cable"
  get 'cobranzas/list'
  get 'cobranzas/new'
  resources :loans
  get 'loans/list'
  get 'loans/create'
  get 'loans/show'
  get 'reportes/ventas'
  get 'reportes/cobros'
  get 'reportes/comisiones'
  get 'reportes/estado'
  get 'reportes/general'
  get 'reportes/almacen'
  get 'reportes/reparaciones'
  get 'reportes/alertas'
  get 'reportes/logs'
  get 'notify/list'
  get 'notify/show/:id', to: "notify#show"
  get '/deudas', to: "cobranzas#deudas"
  resources :alarms
  resources :repairs
  get 'panel/init'
  get 'interative/maps'
  resources :cobros
  resources :pos
  resources :shippings do
    get :barcode, on: :member
    get :entrace, on: :member
    get :goware, on: :member
    get :modified, on: :member

  end
  resources :products
  get 'estadistics/welcome'
  resources :providers
  resources :consortia
  resources :categories
  resources :sectores
  resources :warehouses
  resources :cobradores
  resources :collectors
  resources :modelos
  resources :brands
  resources :zones
  devise_for :users
  root 'welcome#index'

  # Filtros
  get '/products_q', to: "products#search"
  get '/shippings_q', to: "shippings#search"
  get '/alerts_q', to: "alarms#alerts_q"
  get '/consortia_q', to: "consortia#consortia_q"
  get '/loan_q', to: "loans#loan_q"

  # Filtro Reporte
  get '/general_q', to: "reportes#generalQ"
  get '/reparaciones_q', to: "reportes#reparaciones_q"
  get '/logs_q', to: "reportes#logsQ"
  get '/notify_q', to: "notify#notify_q"
  get '/alertas_q', to: "reportes#alertas_q"
  get '/ventas_q', to: "reportes#ventas_q"
  get '/cobros_q', to: "reportes#cobros_q"
  get '/estado_q', to: "reportes#estado_q"
  get '/comisiones_q', to: "reportes#comisiones_q"
  # Saves
  post 'shipping/save', to: "shippings#save"


  namespace :api do

    #==============================================================>
    # Externas:
    #==============================================================>
      #Entrada de efectivo
      get 'setBillIn/:pos/:amount', to: "app#setBillIn"

      #Salida de efectivo
      get 'setBillOut/:pos/:amount', to: "app#setBillOut"

      #Apagar Maquina
      get 'shutdown/:pos', to: "app#shutdown"

      #Encender Maquina
      get 'poweron/:pos', to: "app#powerOn"

      #Buscar la localizacion de la maquina
      get 'getLocation/:pos', to: "app#getLocation"

      #Reportar aproximidad
      get 'setAproximidad/:pos', to: "app#setAproximidad"

      #Reportar Apagado
      get 'setShutDown/:pos', to: "app#setShutDown"

      #Reportar Encendido
      get 'setPowerOn/:pos', to: "app#setPoweOn"

      #Reportar conexion de wifi
      get 'setWifiOn/:pos', to: "app#setWifiOn"

      #Reportar desconexion de wifi
      get 'setWifiOff/:pos', to: "app#setWifiOff"

      #Reportar conexion a datos
      get 'setDataOn/:pos', to: "app#setDataOn"
      
      #Reportar desconexion a datos
      get 'setDataOff/:pos', to: "app#setDataOff"

      #Reporte de localizacion
      get 'setLocations/:pos/:lon/:lat', to: "app#setLocations"

      #Traer la configuracion
      get 'getConfigByNumber/:number', to: "app#getConfigByNumber"
    #==============================================================>
    # TEST
    #==============================================================>
    get 'test/poweroff', to: "app#POWEROFF_TEST"
    get 'test/poweron', to: "app#POWERON_TEST"


    #==============================================================>
    # Internal APIs
    #==============================================================>
    #Traer Prestamos pendientes
    #get 'getPrestamosPendientes/:pos', to: "app#getPrestamosPendientes"

    #Traer direcciones
    get 'getDirections/:zone/:status', to: "app#getDirections"

    # Traer controles
    get 'getControls/:pos', to: "app#getControl"

    # Buscar entrada especifica en almacen
    get 'getEntrance/:q_for/:ref', to: "app#getEntrance"

    # Actualizar Cambios a una entrada en especifico
    get 'changeEntrace/:id/:barcode/:ref', to: "app#changeEntrace"

    # Validando un dispositivo
    post 'CheckDevice/:barcode/:t', to: "app#checkDevice"

    # Metodo para traer las zonas de un cobrador
    post 'getCollectorZone/:c_id', to: "app#getCollectorZone"

    # Metodo para traer POS por zonas
    get 'getPOSZone/:z_id', to: "app#getPOSZone"

    # Metodo para traer zonas
    get 'getZones/', to: "app#getZones"

    # Metodo para traer zonas
    get 'getCasinos/', to: "app#getCasinos"

    # Metodo para traer deuda por POS
    get 'getDebt/:pos', to: "app#getDebt"
    
    #Metodo para traer las zonas de los cobraodres
    get 'getZoneByCobrador/:cobrador', to: "app#getZoneByCobrador"
    #==============================================================>
    #                      CRONS
    #==============================================================>
    get '/crons/GHWK5_Alarms/:token', to: "app#cron_alarms"
    get '/crons/GSWT5_Hours/:token', to: "app#cron_hours"
    get '/crons/GVFT5_Mora/:token', to: "app#cron_moras"

    #==============================================================>
    #                      Estadisticas
    #==============================================================>
    get '/estadisticas/ventas/diaria', to: "app#estVentasDiaria"
    
    #==============================================================>
  
  end

  namespace :internal do

    #verificando dispositvos
    get 'CheckDevice/:barcode/:t', to:"internal#checkDevice"

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :modelos
    has_many :products

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.where(user_id: current_user.id)
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)
    @brand.user_id = current_user.id
    respond_to do |format|
      if @brand.save
        format.html { redirect_to :action => :index, notice: '' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to :action => :index, notice: '' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:user_id, :description, :status)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<nav aria-label="breadcrumb ">
  <ol class="breadcrumb bg-black">
    <li class="breadcrumb-item"><a href="/brands">Marcas</a></li>
    <li class="breadcrumb-item active" aria-current="page">Agregar / Editar</li>
  </ol>
</nav>

<center>
<div class="card card-body bg-white col-md-6">
<h2 class="text-muted">Marca - Agregar / Editar</h2>
<hr>
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <table class="table table-striped table-hover">
 <thead class="bg-red text-white">
  <th>Descripcion</th>  <th>Estado</th>

  </thead>
  <tbody>
  <tr>
  <td>
      <%= form.text_field :description, class:"form-control", placeholder:"Nombre de la Marca" %>

  </td>
    <td>
   <%= form.select :status, [["Activa","1"],["Inactiva","2"]], class:"form-control" %>

  </td>
  </tr>
  </tbody>
  </table>





  <div class="actions">
    <%= form.submit "Grabar", class:"btn btn-success" %>
    <%= link_to 'Cancelar', brands_path, class:"btn btn-danger" %>

  </div>


<% end %>

</div>
</center>

app/views/brands/edit.html.erb
<%= render 'form', brand: @brand %>

app/views/brands/index.html.erb
<nav aria-label="breadcrumb ">
  <ol class="breadcrumb bg-black">
    <li class="breadcrumb-item"><a href="#">Mantenimientos</a></li>
    <li class="breadcrumb-item active" aria-current="page">Marcas</li>
  </ol>
</nav>

<div class="card card-body bg-white">
<h2 class="text-muted">Marcas</h2>
<hr>

 <table class="table table-striped table-hover">
        <thead class="bg-red text-white">
    <tr>
      <th>Code</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.id %></td>
        <td><%= brand.description %></td>
         <td>
        
        <% if brand.status == 1 %>
        <span class="badge badge-primary">Activa</span>
        <% else %>
        <span class="badge badge-danger">Desactivada</span>

        <% end %>

        </td>
        <td><%= link_to 'Editar', edit_brand_path(brand),  class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="m1">

<%= link_to 'Crear Marca', new_brand_path, class:"btn btn-primary" %>

</div>

</div>

app/views/brands/new.html.erb
<%= render 'form', brand: @brand %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @brand.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @brand.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @brand.status %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>