config/routes.rb
Rails.application.routes.draw do
  get 'bloqueos/index'
  mount ActionCable.server => "/cable"
  get 'cobranzas/list'
  get 'cobranzas/new'
  resources :loans
  get 'loans/list'
  get 'loans/create'
  get 'loans/show'
  get 'reportes/ventas'
  get 'reportes/cobros'
  get 'reportes/comisiones'
  get 'reportes/estado'
  get 'reportes/general'
  get 'reportes/almacen'
  get 'reportes/reparaciones'
  get 'reportes/alertas'
  get 'reportes/logs'
  get 'notify/list'
  get 'notify/show/:id', to: "notify#show"
  get '/deudas', to: "cobranzas#deudas"
  resources :alarms
  resources :repairs
  get 'panel/init'
  get 'interative/maps'
  resources :cobros
  resources :pos
  resources :shippings do
    get :barcode, on: :member
    get :entrace, on: :member
    get :goware, on: :member
    get :modified, on: :member

  end
  resources :products
  get 'estadistics/welcome'
  resources :providers
  resources :consortia
  resources :categories
  resources :sectores
  resources :warehouses
  resources :cobradores
  resources :collectors
  resources :modelos
  resources :brands
  resources :zones
  devise_for :users
  root 'welcome#index'

  # Filtros
  get '/products_q', to: "products#search"
  get '/shippings_q', to: "shippings#search"
  get '/alerts_q', to: "alarms#alerts_q"
  get '/consortia_q', to: "consortia#consortia_q"
  get '/loan_q', to: "loans#loan_q"

  # Filtro Reporte
  get '/general_q', to: "reportes#generalQ"
  get '/reparaciones_q', to: "reportes#reparaciones_q"
  get '/logs_q', to: "reportes#logsQ"
  get '/notify_q', to: "notify#notify_q"
  get '/alertas_q', to: "reportes#alertas_q"
  get '/ventas_q', to: "reportes#ventas_q"
  get '/cobros_q', to: "reportes#cobros_q"
  get '/estado_q', to: "reportes#estado_q"
  get '/comisiones_q', to: "reportes#comisiones_q"
  # Saves
  post 'shipping/save', to: "shippings#save"


  namespace :api do

    #==============================================================>
    # Externas:
    #==============================================================>
      #Entrada de efectivo
      get 'setBillIn/:pos/:amount', to: "app#setBillIn"

      #Salida de efectivo
      get 'setBillOut/:pos/:amount', to: "app#setBillOut"

      #Apagar Maquina
      get 'shutdown/:pos', to: "app#shutdown"

      #Encender Maquina
      get 'poweron/:pos', to: "app#powerOn"

      #Buscar la localizacion de la maquina
      get 'getLocation/:pos', to: "app#getLocation"

      #Reportar aproximidad
      get 'setAproximidad/:pos', to: "app#setAproximidad"

      #Reportar Apagado
      get 'setShutDown/:pos', to: "app#setShutDown"

      #Reportar Encendido
      get 'setPowerOn/:pos', to: "app#setPoweOn"

      #Reportar conexion de wifi
      get 'setWifiOn/:pos', to: "app#setWifiOn"

      #Reportar desconexion de wifi
      get 'setWifiOff/:pos', to: "app#setWifiOff"

      #Reportar conexion a datos
      get 'setDataOn/:pos', to: "app#setDataOn"
      
      #Reportar desconexion a datos
      get 'setDataOff/:pos', to: "app#setDataOff"

      #Reporte de localizacion
      get 'setLocations/:pos/:lon/:lat', to: "app#setLocations"

      #Traer la configuracion
      get 'getConfigByNumber/:number', to: "app#getConfigByNumber"
    #==============================================================>
    # TEST
    #==============================================================>
    get 'test/poweroff', to: "app#POWEROFF_TEST"
    get 'test/poweron', to: "app#POWERON_TEST"


    #==============================================================>
    # Internal APIs
    #==============================================================>
    #Traer Prestamos pendientes
    #get 'getPrestamosPendientes/:pos', to: "app#getPrestamosPendientes"

    #Traer direcciones
    get 'getDirections/:zone/:status', to: "app#getDirections"

    # Traer controles
    get 'getControls/:pos', to: "app#getControl"

    # Buscar entrada especifica en almacen
    get 'getEntrance/:q_for/:ref', to: "app#getEntrance"

    # Actualizar Cambios a una entrada en especifico
    get 'changeEntrace/:id/:barcode/:ref', to: "app#changeEntrace"

    # Validando un dispositivo
    post 'CheckDevice/:barcode/:t', to: "app#checkDevice"

    # Metodo para traer las zonas de un cobrador
    post 'getCollectorZone/:c_id', to: "app#getCollectorZone"

    # Metodo para traer POS por zonas
    get 'getPOSZone/:z_id', to: "app#getPOSZone"

    # Metodo para traer zonas
    get 'getZones/', to: "app#getZones"

    # Metodo para traer zonas
    get 'getCasinos/', to: "app#getCasinos"

    # Metodo para traer deuda por POS
    get 'getDebt/:pos', to: "app#getDebt"
    
    #Metodo para traer las zonas de los cobraodres
    get 'getZoneByCobrador/:cobrador', to: "app#getZoneByCobrador"
    #==============================================================>
    #                      CRONS
    #==============================================================>
    get '/crons/GHWK5_Alarms/:token', to: "app#cron_alarms"
    get '/crons/GSWT5_Hours/:token', to: "app#cron_hours"
    get '/crons/GVFT5_Mora/:token', to: "app#cron_moras"

    #==============================================================>
    #                      Estadisticas
    #==============================================================>
    get '/estadisticas/ventas/diaria', to: "app#estVentasDiaria"
    
    #==============================================================>
  
  end

  namespace :internal do

    #verificando dispositvos
    get 'CheckDevice/:barcode/:t', to:"internal#checkDevice"

  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/repair.rb
class Repair < ApplicationRecord
    belongs_to :po
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.where(user_id: current_user.id)
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(repair_params)
    @repair.user_id = current_user.id
    respond_to do |format|
      if @repair.save
        
        @pos = Po.find(@repair.po_id)
        @pos.status = 3
        @pos.save 

        RepairLog.create({repair_id: @repair.id, comment: @repair.description, po_id: @repair.po_id})

        format.html { redirect_to repairs_url, notice: 'Repair was successfully created.' }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @pos = Po.find(@repair.po_id)
    @pos.status = 1
    @pos.save 

    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url, notice: 'Repair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:user_id, :po_id, :description)
    end
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/_form.html.erb
<nav aria-label="breadcrumb ">
  <ol class="breadcrumb bg-black">
    <li class="breadcrumb-item"><a href="/repairs">Reparaciones</a></li>
    <li class="breadcrumb-item active" aria-current="page">Agregar / Editar</li>
  </ol>
</nav>

<div class="card card-body bg-white col-md-12">
<h2 class="text-muted">Reparaciones</h2>
<hr>

<%= form_with(model: repair, local: true) do |form| %>
  <% if repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% repair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <table class="table table-striped table-hover">
 <thead class="" style="background-color:#191b1c; color:yellow;">
    <th>Punto de Venta</th><th>Motivos</th>
  </thead>

  <tbody>
  <tr>
  <td>
    <%=
    form.collection_select(
    :po_id, 
    Po.where(user_id: current_user.id).where(status: 1), 
    :id,
    :description, 
    :prompt => false
    )
  %>
  </td>
  <td>
  <%= form.text_field :description %>
  </td>
  </tr>
  </tbody>
  </table>
  <div class="field">
    
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class:"btn btn-primary float-left" %>
    <%= link_to  "Cancelar", repairs_path, class:"btn btn-danger" %>
  </div>
<% end %>



</div>

<script>

$("select").select2({width: 250});
</script>

app/views/repairs/edit.html.erb
<%= render 'form', repair: @repair %>

app/views/repairs/index.html.erb
<div style="width:100%; min-height:70px; background-color:white;margin-top:-20px;">
<h3 class="float-left" style="margin-left:10px; margin-top:20px;">Máquinas en Reparación</h3>
<hr>
</div>



<div class="row">
    <% @repairs.each do |repair| %>
     <div class="card card-body col-md-3" style="margin:10px;">

     <center>
      <i class="fa fa-laptop" style="font-size:27px;"></i><br><br>
        <a href="/pos/<%=repair.po_id%>"><h6><%=repair.po.description%></h6></a><br>
          <%= link_to 'Produccion', repair, method: :delete, data: { confirm: '¿Seguro que desea por maquina devuelta a produccion?' }, class:"btn btn-danger" %>
   
     </center>
        

     
     </div>
    <% end %>


<br>

<div class="card card-body col-md-3 " style="margin:10px; cursor:pointer;" id="add_r">
<center>
<i class="fa fa-plus" style="font-size:68px; margin-top:15px;"></i>
</center>
</div>

</div>


<script>
$("#add_r").click(function(){
window.location = "repairs/new";
});
</script>

app/views/repairs/new.html.erb
<%= render 'form', repair: @repair %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @repair.user_id %>
</p>

<p>
  <strong>Po:</strong>
  <%= @repair.po_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repair.description %>
</p>

<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>